_target_: neural_signatures.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset_specification:
  _target_: neural_signatures.data_modules.synthetic_data_modules.DatasetSpecification
  dataset:
    _target_: neural_signatures.datasets.synthetic_datasets.NoisySphereSurfaceDataset
    epoch_size: ${globals.train_epoch_size}
    grid_points_count: ${globals.grid_points_count}
    grid_range: ${globals.grid_range}
    sampling_ratio_range: ${globals.sampling_ratio_range}
    anchors_ratio_range: ${globals.anchors_ratio_range}
    use_autograd: False
    canonical_pose: ${globals.canonical_pose}
    sampled_patches: 2
    max_ring: null
    seed: 11

    add_unsampled_patch: ${globals.add_unsampled_patch}
    conv_k_nearest: ${globals.conv_k_nearest}

    deform_k_nearest: ${globals.deform_k_nearest}
    deform_iterations: ${globals.deform_iterations}
    deform_actions_per_iteration: ${globals.deform_actions_per_iteration}
    deform_delta: ${globals.deform_delta}

    radius_range: ${globals.radius_range}
    subdivisions_range: ${globals.subdivisions_range}
    noise_scale_range: ${globals.noise_scale_range}
    affine_scale_range: ${globals.affine_scale_range}
    amplitude_range: ${globals.amplitude_range}
    octaves_range: ${globals.octaves_range}
    persistence_range: ${globals.persistence_range}
    lacunarity_range: ${globals.lacunarity_range}
  batch_size: ${globals.noisy_sphere_train_batch_size}
  num_workers: ${globals.noisy_sphere_train_num_workers}
  shuffle: True
val_dataset_specifications:
#  - _target_: neural_signatures.data_modules.synthetic_data_modules.DatasetSpecification
#    dataset:
#      _target_: neural_signatures.datasets.synthetic_datasets.NoisySphereSurfaceDataset
#      epoch_size: ${globals.train_epoch_size}
#      grid_points_count: ${globals.grid_points_count}
#      grid_range: ${globals.grid_range}
#      sampling_ratio_range: ${globals.sampling_ratio_range}
#      anchors_ratio: ${globals.anchors_ratio}
#      use_autograd: False
#      canonical_pose: ${globals.canonical_pose}
#      sampled_patches: 2
#      max_ring: null
#      seed: 11
#
#      add_unsampled_patch: ${globals.add_unsampled_patch}
#      conv_k_nearest: ${globals.conv_k_nearest}
#
#      deform_k_nearest: ${globals.deform_k_nearest}
#      deform_iterations: ${globals.deform_iterations}
#      deform_actions_per_iteration: ${globals.deform_actions_per_iteration}
#      deform_delta: ${globals.deform_delta}
#
#      radius_range: ${globals.radius_range}
#      subdivisions_range: ${globals.subdivisions_range}
#      noise_scale_range: ${globals.noise_scale_range}
#      affine_scale_range: ${globals.affine_scale_range}
#      amplitude_range: ${globals.amplitude_range}
#      octaves_range: ${globals.octaves_range}
#      persistence_range: ${globals.persistence_range}
#      lacunarity_range: ${globals.lacunarity_range}
#    batch_size: ${globals.noisy_sphere_val_batch_size}
#    num_workers: ${globals.noisy_sphere_val_num_workers}
#    shuffle: False
  - _target_: neural_signatures.data_modules.synthetic_data_modules.DatasetSpecification
    dataset:
      _target_: neural_signatures.datasets.mesh_datasets.Shrec19Dataset
      pairs_file_path: ${globals.shrec19_pairs_file_path}
      meshes_dir_path: ${globals.shrec19_meshes_dir_path}
      correspondences_dir_path: ${globals.shrec19_correspondences_dir_path}
      conv_k_nearest: ${globals.conv_k_nearest}
    batch_size: ${globals.shrec19_batch_size}
    num_workers: ${globals.shrec19_num_workers}
    shuffle: False