_target_: neural_signatures.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset:
  _target_: neural_signatures.datasets.synthetic_datasets.NoisySphereSurfaceDataset
  epoch_size: ${globals.train_epoch_size}
  grid_points_count: ${globals.grid_points_count}
  grid_range: ${globals.grid_range}
  sampling_ratio_range: ${globals.sampling_ratio_range}
  anchors_ratio: ${globals.anchors_ratio}
  use_autograd: False
  canonical_pose: ${globals.canonical_pose}
  sampled_patches: 2
  max_ring: null
  seed: 11

  add_unsampled_patch: True
  deform_k_nearest: 20
  deform_iterations: 5
  deform_actions_per_iteration: 4
  deform_delta: 0.05

  radius_range: [1, 2]
  subdivisions_range: [5, 6]
  noise_scale_range: [0.8, 1.2]
  affine_scale_range: [0.7, 1.3]
  amplitude_range: [0.5, 1.5]
  octaves_range: [1, 3]
  persistence_range: [0.5, 1.5]
  lacunarity_range: [1.0, 4.0]

val_dataset: null
val_mesh_dataset: null
batch_size: ${globals.batch_size}
num_workers: ${globals.num_workers}