_target_: neural_signatures.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset:
  _target_: neural_signatures.datasets.synthetic_datasets.RbfSurfaceDataset
  epoch_size: ${globals.train_epoch_size}
  grid_points_count: ${globals.grid_points_count}
  grid_range: ${globals.grid_range}
  sampling_ratio_range: ${globals.sampling_ratio_range}
  anchors_ratio: ${globals.anchors_ratio}
  use_autograd: False
  canonical_pose: ${globals.canonical_pose}
  sampled_patches: 2
  max_ring: null
  seed: 42
  grid_generation_method: ${globals.grid_generation_method}
  add_unsampled_patch: True
  rbf_num_points_range: ${globals.rbf_num_points_range}
  xy_means_range: ${globals.xy_means_range}
  xy_stds_range: ${globals.xy_stds_range}
  z_means_range: ${globals.z_means_range}
  z_stds_range: ${globals.z_stds_range}
  epsilon_range: ${globals.epsilon_range}
val_dataset: null
val_mesh_dataset: null
batch_size: ${globals.batch_size}
num_workers: ${globals.num_workers}