_target_: neural_signatures.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset_specification:
  _target_: neural_signatures.data_modules.synthetic_data_modules.DatasetSpecification
  dataset:
    _target_: neural_signatures.datasets.synthetic_datasets.PolynomialSurfaceDataset
    epoch_size: ${globals.train_epoch_size}
    grid_points_count: ${globals.grid_points_count}
    grid_generation_method: ${globals.grid_generation_method}
    grid_radius_range: ${globals.grid_radius_range}
    grid_offset_range: ${globals.grid_offset_range}
    points_scale_range: ${globals.points_scale_range}
    sampling_ratio_range: ${globals.sampling_ratio_range}
    features_type: ${globals.features_type}
    pose_type: ${globals.pose_type}
    use_autograd: False
    sampled_patches: 2
    max_ring: null
    seed: ${globals.seed}
    add_regularized_mesh: False
    order_range: ${globals.order_range}
    coefficient_scale_range: ${globals.coefficient_scale_range}
    coeff_generation_method: ${globals.coeff_generation_method}
    deform: False
    deform_k_nearest: null
    deform_iterations: null
    deform_actions_per_iteration: null
    deform_delta: null
    conv_k_nearest: null
  batch_size: ${globals.train_batch_size}
  num_workers: ${globals.train_num_workers}
  shuffle: True
val_dataset_specifications:
  - _target_: neural_signatures.data_modules.synthetic_data_modules.DatasetSpecification
    dataset:
      _target_: neural_signatures.datasets.synthetic_datasets.PolynomialSurfaceDataset
      epoch_size: ${globals.val_epoch_size}
      grid_points_count: ${globals.grid_points_count}
      grid_generation_method: ${globals.grid_generation_method}
      grid_radius_range: ${globals.grid_radius_range}
      grid_offset_range: ${globals.grid_offset_range}
      points_scale_range: ${globals.points_scale_range}
      sampling_ratio_range: ${globals.sampling_ratio_range}
      features_type: ${globals.features_type}
      pose_type: ${globals.pose_type}
      use_autograd: False
      sampled_patches: 2
      max_ring: null
      seed: ${globals.seed}
      add_regularized_mesh: False
      order_range: ${globals.order_range}
      coefficient_scale_range: ${globals.coefficient_scale_range}
      coeff_generation_method: ${globals.coeff_generation_method}
      deform: False
      deform_k_nearest: null
      deform_iterations: null
      deform_actions_per_iteration: null
      deform_delta: null
      conv_k_nearest: null
    batch_size: ${globals.val_batch_size}
    num_workers: ${globals.val_num_workers}
    shuffle: False
  - _target_: neural_signatures.data_modules.synthetic_data_modules.DatasetSpecification
    dataset:
      _target_: neural_signatures.datasets.mesh_datasets.GeodesicPatchesDataset
      root_dirs:
        - './benchmarks/SCAPE_r/off'
      remesh_configs:
        - _target_: neural_signatures.datasets.mesh_datasets.RemeshConfig
          method_name: 'meshing_isotropic_explicit_remeshing'
          method_kwargs:
            iterations: 10
            targetlen:
              _target_: pymeshlab.PercentageValue
              _args_: [2.0]
            adaptive: True
      features_type: ${globals.features_type}
      pose_type: ${globals.pose_type}
      file_size_threshold: 1
      radius: 0.06
      corresponding_points_count: 1000
      file_count_limit: 2
    batch_size: ${globals.geodesic_patches_val_batch_size}
    num_workers: ${globals.geodesic_patches_val_num_workers}
    shuffle: False
