_target_: neural_local_laplacian.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset_specification:
  _target_: neural_local_laplacian.data_modules.synthetic_data_modules.DatasetSpecification
  dataset:
    _target_: neural_local_laplacian.datasets.synthetic_datasets.PolynomialSurfaceDataset
    seed: ${globals.seed}
    epoch_size: 1000
    sampled_surfaces: 2
    grid_points_count: 1000
    grid_radius_range: [0.7]
    grid_offset_range: [-0.01, 0.01]
    points_scale_range: [1, 1.01]
    sampling_ratio_range: [0.04, 0.5]
    coefficient_scale_range: [0.9, 0.91]
    order_range: [2, 5]
    add_regularized_surface: True
    conv_k_nearest: null
    grid_generation_method:
      _target_: neural_local_laplacian.datasets.synthetic_datasets.GridGenerationMethod
      _args_: ['uniform']
    features_type:
      _target_: neural_local_laplacian.datasets.synthetic_datasets.FeaturesType
      _args_: ['xyz']
    pose_type:
      _target_: neural_local_laplacian.datasets.synthetic_datasets.PoseType
      _args_: ['pca']
    coeff_generation_method:
      _target_: neural_local_laplacian.datasets.synthetic_datasets.CoeffGenerationMethod
      _args_: ['uniform']
    diff_geom_components:
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['mean_curvature']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['gaussian_curvature']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['principal_curvatures']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['principal_directions']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['mean_curvature']
  batch_size: 1
  num_workers: 0
  shuffle: True
val_dataset_specifications: null