_target_: neural_local_laplacian.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset_specification:
  _target_: neural_local_laplacian.data_modules.synthetic_data_modules.DatasetSpecification
  dataset:
    _target_: neural_local_laplacian.datasets.synthetic_datasets.PolynomialSurfaceDataset
    epoch_size: ${globals.train_epoch_size}
    grid_points_count: ${globals.grid_points_count}
    grid_generation_method: ${globals.grid_generation_method}
    grid_radius_range: ${globals.grid_radius_range}
    grid_offset_range: ${globals.grid_offset_range}
    points_scale_range: ${globals.points_scale_range}
    sampling_ratio_range: ${globals.sampling_ratio_range}
    features_type: ${globals.features_type}
    pose_type: ${globals.pose_type}
    use_autograd: True
    sampled_patches: 1
    max_ring: null
    seed: ${globals.seed}
    add_regularized_mesh: False
    order_range: ${globals.order_range}
    coefficient_scale_range: ${globals.coefficient_scale_range}
    coeff_generation_method: ${globals.coeff_generation_method}
    deform: False
    deform_k_nearest: null
    deform_iterations: null
    deform_actions_per_iteration: null
    deform_delta: null
    conv_k_nearest: null
  batch_size: ${globals.train_batch_size}
  num_workers: ${globals.train_num_workers}
  shuffle: True
val_dataset_specifications: null

