module:
  _target_: neural_local_laplacian.modules.laplacian_modules.SurfaceTransformerModule
  input_dim: 1024
  d_model: 512
  nhead: 8
  num_encoder_layers: 4
  dim_feedforward: 2048
  dropout: 0.1