_target_: neural_signatures.modules.unsupervised_modules.SoftCorrespondenceModule
mlp_cfg:
  _target_: neural_signatures.modules.architectures.ConfigurableMLP
  _partial_: True
  channels: [14, 64, 256]
  use_batch_norm: True
  activation: torch.nn.GELU
gnn_cfg:
  _target_: deltaconv.models.DeltaNetBase
  _partial_: True
  conv_channels: [256, 256, 512, 512]
  mlp_depth: 2
  num_neighbors: 20
  grad_regularizer: 0.001
  grad_kernel_width: 1
sinkhorn_temp: 0.2
sinkhorn_n_iter: 10
sinkhorn_slack: False
pooling_layers: null
gnn_channels_key: 'channels'
gnn_channels_concat: True
