_target_: neural_signatures.modules.unsupervised_modules.SimSiamSignaturePredictionModule
gnn_cfg:
  _target_: deltaconv.models.DeltaNetBase
  _partial_: True
  in_channels: 3
  conv_channels: [64, 64, 128, 256]
  mlp_depth: 2
  num_neighbors: 20
  grad_regularizer: 0.001
  grad_kernel_width: 1
prepooling_mlp_cfg: null
pooling_layers: ['torch_geometric.nn.global_mean_pool', 'torch_geometric.nn.global_max_pool']
postpooling_mlp_cfg:
  _target_: 'neural_signatures.modules.architectures.ConfigurableMLP'
  _partial_: True
  channels: [256, 128]
  use_batch_norm: True
  activation: 'torch.nn.GELU'
gnn_channels_key: 'conv_channels'
gnn_channels_concat: True
criterion:
  _target_: 'lightly.loss.NegativeCosineSimilarity'