name: neural-local-laplacian
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.12
  - cython
  - eigen
  - cmake
  - pip:
    - -r requirements_cu124.txt