_target_: pytorch_lightning.Trainer
max_epochs: -1
devices: 1
accelerator: 'auto'
strategy: 'auto'
num_sanity_val_steps: 0
log_every_n_steps: 1
check_val_every_n_epoch: 20
enable_progress_bar: True
logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: neural-signatures
  save_dir: 'wandb'
  log_model: 'all'
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: 'checkpoints'
    filename: 'val_top1_rate_dataloader0'
    save_top_k: 1
    verbose: False
    monitor: 'val_top1_rate_dataloader0'
    mode: 'max'
