seed: 42
grid_points_count: 1000
order_range: [2, 4]

grid_radius_range: [1.0]
grid_offset_range: [-0.01, 0.01]
coefficient_scale_range: [0.5, 2.0]
sampling_ratio_range: [0.025, 0.5]
points_scale_range: [1.0, 1.01]

coeff_generation_method:
  _target_: neural_signatures.datasets.synthetic_datasets.CoeffGenerationMethod
  _args_: ['uniform']
grid_generation_method:
  _target_: neural_signatures.datasets.synthetic_datasets.GridGenerationMethod
  _args_: ['uniform']
features_type:
  _target_: neural_signatures.datasets.synthetic_datasets.FeaturesType
  _args_: ['risp']
pose_type:
  _target_: neural_signatures.datasets.synthetic_datasets.PoseType
  _args_: ['random_rotation']
