defaults:
  - polynomial_patches_risp@_here_

train_batch_size: 128
train_epoch_size: 1024
train_num_workers: 15

val_batch_size: 128
val_epoch_size: 1024
val_num_workers: 15

geodesic_patches_val_batch_size: 128
geodesic_patches_val_num_workers: 0

lr: 2e-3
ckpt_path: null
#ckpt_path: "./checkpoints/epoch=639-val_top1_rate=0.02.ckpt"