defaults:
  - polynomial_patches@_here_

train_batch_size: 16
train_epoch_size: 16
train_num_workers: 0

val_batch_size: 16
val_epoch_size: 16
val_num_workers: 0

geodesic_patches_val_batch_size: 16
geodesic_patches_val_epoch_size: 16
geodesic_patches_val_num_workers: 0

lr: 1e-3
ckpt_path: null
#ckpt_path: "./checkpoints/epoch=639-val_top1_rate=0.02.ckpt"