#batch_size: 5
train_epoch_size: 64
val_epoch_size: 1
#num_workers: 0
lr: 1e-3
seed: 42
grid_points_count: 10000
visualization: False
canonical_pose: False
order_range: [5, 7]
sampling_ratio_range: [0.2, 0.7]
anchors_ratio_range: [0.01, 0.02]
grid_radius: 600
grid_range: ["${multiply:${globals.grid_radius},-1}", "${globals.grid_radius}"]
k: 10
coefficient_scale_range: [0.5, 2]
coeff_generation_method:
  _target_: neural_signatures.datasets.synthetic_datasets.CoeffGenerationMethod
  _args_: ['uniform']
grid_generation_method:
  _target_: neural_signatures.datasets.synthetic_datasets.GridGenerationMethod
  _args_: ['uniform']
rbf_num_points_range: [20, 100]
xy_means_range: ${globals.grid_range}
xy_stds_range: [0.1, "${globals.grid_radius}"]
z_means_range: [-10, 10]
z_stds_range: [1, 200]
epsilon_range: [0.1, 1]

add_unsampled_patch: False
conv_k_nearest: 20

deform_k_nearest: 20
deform_iterations: 3
deform_actions_per_iteration: 5
deform_delta: 0.1

radius_range: [1, 2]
subdivisions_range: [5, 6]
noise_scale_range: [0.8, 1.2]
affine_scale_range: [0.7, 1.3]
amplitude_range: [0.5, 1.5]
octaves_range: [1, 3]
persistence_range: [0.5, 1.5]
lacunarity_range: [1.0, 4.0]

noisy_sphere_train_num_workers: 32
noisy_sphere_val_num_workers: 0
shrec19_num_workers: 5

noisy_sphere_train_batch_size: 8
noisy_sphere_val_batch_size: 1
shrec19_batch_size: 2

shrec19_pairs_file_path: "./benchmarks/shrec19/PAIRS_list_SHREC19_connectivity.txt"
shrec19_meshes_dir_path: "./benchmarks/shrec19/meshes"
shrec19_correspondences_dir_path: "./benchmarks/shrec19/FARMgt_txt"

