defaults:
  - polynomial_patches@_here_

train_batch_size: 1
train_epoch_size: 2048
train_num_workers: 0
val_batch_size: 1
val_epoch_size: 2048
val_num_workers: 0
#grid_radius_range: [1, 2]
#coefficient_scale_range: [0.1, 0.4]
#sampling_ratio_range: [0.1, 0.4]
pose_type:
  _target_: neural_local_laplacian.datasets.synthetic_datasets.PoseType
  _args_: ['none']